---
- name: Install telemetry packages and kcat
  ansible.builtin.import_tasks: packages.yml

- name: Install Kafka cluster CA
  ansible.builtin.import_tasks: ca.yml

- name: Configure SELinux for rsyslog to Kafka
  ansible.builtin.import_tasks: selinux.yml

- name: Configure firewalld
  ansible.builtin.import_tasks: firewall.yml

- name: Configure rsyslog omkafka
  ansible.builtin.import_tasks: rsyslog.yml

- name: Configure PCP and pcp2kafka
  ansible.builtin.import_tasks: pcp.yml
