apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logstream-kafka
resources:
  - serviceaccount.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
