---
- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload hotproc config
  ansible.builtin.command:
    argv:
      - pmstore
      - hotproc.control.reload_config
      - "1"
  changed_when: true

- name: Restart pcp2kafka
  ansible.builtin.systemd:
    name: pcp2kafka
    state: restarted
    daemon_reload: true

- name: Update CA trust
  ansible.builtin.command:
    cmd: update-ca-trust extract
  changed_when: true

- name: Restore CA file context
  ansible.builtin.command:
    cmd: restorecon -v {{ kafka_ca_path }}
  changed_when: true
